[project]
name = "ferrah-custom-nodes"
description = ""
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/FerrahWolfeh/ferrah-custom-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ferrah-custom-nodes"
Icon = ""
